# Array Computations:

NumPy, short for Numerical Python, is the fundamental package required for high performance scientific computing and data analysis. It is the foundation on which nearly all of the higher-level tools are built.
#### Key highlight: 
    1. ndarray, a fast and space-efficient multidimensional array providing vectorized arithmetic operations and  sophisticated broadcasting capabilities.
    2. Standard mathematical functions for fast operations on entire arrays of data without having to write loops
    3. Tools for reading / writing array data to disk and working with memory-mapped files
    4. Linear algebra, random number generation, and Fourier transform capabilities
    5. Tools for integrating code written in C, C++, and Fortran
    
It is very easy to pass data to external libraries written in a low-level language and also for external libraries to return data to Python as NumPy arrays.

While NumPy by itself does not provide very much high-level data analytical functionality, having an understanding of NumPy arrays and array-oriented computing will help you use tools like pandas much more effectively.

For most data analysis applications, the main areas of functionality
    1. Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations
    2. Common array algorithms like sorting, unique, and set operations
    3. Efficient descriptive statistics and aggregating/summarizing data
    4. Data alignment and relational data manipulations for merging and joining together heterogeneous data sets
    5. Expressing conditional logic as array expressions instead of loops with if-elifelse branches.
    6. Group-wise data manipulations (aggregation, transformation, function application).

In [ ]:
!pip install numpy
# If anaconda python is already installed then ignore this command

In [2]:
import numpy as np

In [167]:
data1 = [6.3, 7, 8, 0, 1] #List
arr1 = np.array(data1)

In [169]:
arr1

array([6.3, 7. , 8. , 0. , 1. ])

In [168]:
arr1.shape

(5,)

In [8]:
# The NumPy ndarray: A Multidimensional Array Object

#import package
import numpy as np

#Creating ndarray : 
#The easiest way to create an array is to use the array function. This accepts any sequence- like object 
#(including other arrays) and produces a new NumPy array containingthe passed data
data1 = [6.3, 7, 8, 0, 1] #List
arr1 = np.array(data1)

print("List:", data1)
print("My First Array:", arr1)
print(type(data1))
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)


List: [6.3, 7, 8, 0, 1]
My First Array: [6.3 7.  8.  0.  1. ]
<class 'list'>
<class 'numpy.ndarray'>
1
(5,)
float64


In [9]:
##Nested Sequence, like a list of equal length list, will be converted to multidimensional array
data2 = [[1,2,3,4],
         [5,6,7, 8]]
arr2 = np.array(data2)
print("My First Two Array:\n", arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)


My First Two Array:
 [[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
8


In [14]:
data3 = [[1,2,3],[5,6,7],[5,6,7]]

arr3 = np.array(data3)
print("My First Two Array:\n", arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

My First Two Array:
 [[1 2 3]
 [5 6 7]
 [5 6 7]]
2
(3, 3)
9


In [23]:
data = np.array([[ 0.9526, -0.246 , -0.8856],
                 [ 0.5639, 0.2379, 0.9104]])

print("2 D Array: \n",data)

# Every array has shape - a tuple - indicating the size of ech dimension
print("Shape of an Array : ",data.shape)


#Every array has dtype, an object describing the data type of an array
#Unless explicitly specified, np.array tries to infer a good data type for the array that it creates.
print("Data Type of an Array :",data.dtype)

#Every array has ndim, an object describing the dimension of an array
print("Dimensions of an Array :",data.ndim)

2 D Array: 
 [[ 0.9526 -0.246  -0.8856]
 [ 0.5639  0.2379  0.9104]]
Shape of an Array :  (2, 3)
Data Type of an Array : float64
Dimensions of an Array : 2


In [18]:
np.zeros(shape = (5,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
arr1 = np.zeros(shape = (2,5,4), dtype=np.float16)

In [34]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float16)

In [35]:
arr1.dtype #datatype (int, float, string)

dtype('float16')

In [26]:
arr1.shape

(2, 5, 4)

In [10]:
#In addition to np.array, there are a number of other functions for creating new arrays.

#zeros(): Create array of zeros
print("1D zero Matrix: \n",np.zeros(10))

print("2D zero Matrix: \n",np.zeros((3, 6)))

#ones(): Create array of ones
print("2D ones Matrix: \n",np.ones((2,3)))



1D zero Matrix: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2D zero Matrix: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
2D ones Matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
np.ones(shape = (2,3,4)) # 3D Array 
#shape- (z, x, y)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
np.ones((2,3))*10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [35]:
#empty creates an array withouf initializing it's values to any particular values.

print("3D empty Matrix: \n",np.empty((2, 3, 2)))
#It’s not safe to assume that np.empty will return an array of all zeros. 
#In many cases, it will return uninitialized garbage values.
print(np.empty((2, 3, 2)).ndim)

3D empty Matrix: 
 [[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 1.69119737e-306]
  [1.24610723e-306 1.33508845e-306]]

 [[1.33511969e-306 6.23037996e-307]
  [6.23053954e-307 9.79107872e-307]
  [8.34445562e-308 8.34402698e-308]]]
3


In [30]:
print("3D empty Matrix: \n",np.zeros((2, 3, 2)))
print("3D empty Matrix: \n",np.empty((4, 2, 3)))

3D empty Matrix: 
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3D empty Matrix: 
 [[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.69119737e-306 1.24610723e-306 1.42413555e-306]]

 [[1.78019082e-306 1.37959740e-306 6.23057349e-307]
  [1.78020848e-306 1.86922094e-306 1.33511018e-306]]

 [[1.33511969e-306 6.23037996e-307 6.23053954e-307]
  [9.34609790e-307 8.45593934e-307 9.34600963e-307]]

 [[1.86921143e-306 6.23061763e-307 6.23053954e-307]
  [1.24611266e-306 2.22522596e-306 2.22522596e-306]]]


In [27]:
np.ones((4,4))*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [12]:
np.full(shape=(4,4),fill_value=10) # shape = (4,4) and ndim = 2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [45]:
np.eye(2) # Identity Matrix

array([[1., 0.],
       [0., 1.]])

##### np.arange(): arange is an array-valued version of the built-in Python range function

In [41]:
list(range(6,10, 2))

[6, 8]

In [13]:
array1 = np.arange(15)
print(array1)
print(type(array1))
print(array1.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
int32


In [48]:
# create numpy array with equal spacing
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [40]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 15, 5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [42]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# NumPy Array Attributes

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [100]:
np.random.randint(10)

array([-0.87035484, -1.21829803, -1.28573011,  0.74783402,  1.09408296,
        1.85377346, -1.51285882,  1.35935488, -0.7828129 , -0.61936817])

In [138]:
np.random.seed(100)
x1 = np.random.randint(low = 10, high= 20, size=(2,3), dtype=np.int16)
print(x1)

[[18 18 10]
 [13 13 17]]


In [104]:
np.round(np.random.randn(10), 2)

array([ 1.18,  0.59, -1.5 , -1.66, -0.84,  0.36, -1.89,  1.31, -0.28,
       -1.22])

In [131]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(low = 10, high= 20, size=6)  # One-dimensional array
x2 = np.random.randint(low = 10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(low = 5, size=(6, 4, 5))  # Three-dimensional array
print(x1)
print(x2)
print(x3)
#print(x3)

[15 10 13 13 17 19]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[0 1 1 0 1]
  [4 3 0 3 0]
  [2 3 0 1 3]
  [3 3 0 1 1]]

 [[1 0 2 4 3]
  [3 2 4 2 0]
  [0 4 0 4 1]
  [4 1 2 2 0]]

 [[1 1 1 1 3]
  [3 2 3 0 3]
  [4 1 2 4 3]
  [4 4 4 3 4]]

 [[4 4 0 4 3]
  [2 0 1 1 3]
  [0 0 1 2 4]
  [2 0 3 2 2]]

 [[0 1 0 2 2]
  [3 2 3 2 1]
  [2 3 3 3 2]
  [3 4 1 2 3]]

 [[1 2 1 4 2]
  [3 0 3 2 3]
  [0 0 0 3 2]
  [3 0 4 0 0]]]


In [132]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (6, 4, 5)
x3 size:  120


Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array:

In [133]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 480 bytes


## Data Types:
Dtypes are part of what make NumPy so powerful and flexible. In most cases they map directly onto an underlying 
machine representation, which makes it easy to read and write binary streams of data to disk and also to connect to code written in a low-level language like C or Fortran. The numerical dtypes are named the same way: a type name,
like float or int, followed by a number indicating the number of bits per element. A standard double-precision floating point value takes up 8 bytes or 64 bits. Thus, this type is known in NumPy as float64.

In [139]:
arr2 = np.array([1, 2, "Hello"]) # integer and string

In [140]:
arr2 # array with all string values

array(['1', '2', 'Hello'], dtype='<U11')

In [145]:
arr2 = np.array([1, 2, "Hello"], dtype = int) # integer and string # forcing to create an integer array

ValueError: invalid literal for int() with base 10: 'Hello'

In [146]:
arr2 = np.array(['1', '2', '3'], dtype = "int")

In [147]:
arr2

array([1, 2, 3])

In [92]:
## Datatype of ndarray
#The data type or dtype is a special object containing the information the ndarray needs 
#to interpret a chunk of memory as a particular type of data:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3], dtype=float)
arr3 = np.array([1.5, 2.3, 3.2])
arr4 = np.array([1.5, 2.3, 3.2], dtype=int)

print("Data Type of arr1:\n",arr1.dtype)
print("Data Type of arr2:\n",arr2.dtype)
print("Data Type of arr3:\n",arr3.dtype)
print("Data Type of arr4:\n",arr4.dtype)



Data Type of arr1:
 int32
Data Type of arr2:
 float64
Data Type of arr3:
 float64
Data Type of arr4:
 int32


In [109]:
##You can explicitly convert of cast an array from one type to another using ndarray's as type method:

arr = np.array([1,2,3,4,5])
print("Original Datatype : ",arr.dtype)

float_arr = arr.astype(float)
print("Data type After Type Casting : ",float_arr.dtype)

##If you cast some floating point numbers to be of integer dtype, the decimal part will be truncated

arr = np.array([1.2,2.1,3.4,4,4])
print("Original Data TYpe : ",arr.dtype)

arr_int = arr.astype(np.int32)
print("Type Casted Data Type:\n",arr_int)




Original Datatype :  int32
Data type After Type Casting :  float64
Original Data TYpe :  float64
Type Casted Data Type:
 [1 2 3 4 4]


In [110]:
##If casting were to fail for some reason, a TypeError will be raised

import numpy as np
numeric_strings = np.array(['Hello','-9.6','42'],dtype=np.string_)
print(numeric_strings.astype(np.float32))


ValueError: could not convert string to float: 'Hello'

In [148]:
numeric_strings = np.array(['-9.6','42'])

In [149]:
numeric_strings

array(['-9.6', '42'], dtype='<U4')

In [150]:
numeric_strings.astype("float") # Helps in typecasting

array([-9.6, 42. ])

In [11]:
# NumPy is smart enough to alias the Python types to the equivalent dtypes
import numpy as np
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))
print(numeric_strings.astype(float).dtype)
print(numeric_strings.astype('float32').dtype)
print(numeric_strings.astype('float64').dtype)

[ 1.25 -9.6  42.  ]
float64
float32
float64


### Points to Remember:

1. Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.


In [151]:
##Operations

#Arrays are important because they enable you to express batch operations on data
#without writing any for loops. This is usually called vectorization. Any arithmetic operations
#between equal-size arrays applies the operation elementwise:
import numpy as np

arr = np.array([[1., 2., 3.], 
                [4., 5., 6.]]) 

#Addition
print("#########Addition#########")
arr1 = arr + arr
print(arr1)

#Subtraction
print("#########Subtraction#########")
arr2 = arr - arr
print(arr2)

#Multiplication
print("#########Multiplicaton#########")
arr3 = arr * arr
print(arr3)

#Division
print("#########Division#########")
arr4 = arr / arr
print(arr4)


#########Addition#########
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
#########Subtraction#########
[[0. 0. 0.]
 [0. 0. 0.]]
#########Multiplicaton#########
[[ 1.  4.  9.]
 [16. 25. 36.]]
#########Division#########
[[1. 1. 1.]
 [1. 1. 1.]]


In [152]:
# Adding matrices of different shapes is not allowed
arr1 = np.array([[1., 2., 3.], 
                 [4., 5., 6.]]) # 2x3

arr2 = np.array([[1., 2.], 
                 [4., 5.]]) # 2x2
arr1+arr2

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [159]:
## Arithmetic Operations with Scalar

##Addition

print(arr)
print("Scalar Addition")
print(arr+1)

print("Scalar Subtraction")
print(arr-1)

print("Scalar Multiplication")
print(arr*2)

print("Scalar Division")
print(1/arr)
print(arr/2)


##Operations between differently sized arrays is called broadcasting

[[1. 2. 3.]
 [4. 5. 6.]]
Scalar Addition
[[2. 3. 4.]
 [5. 6. 7.]]
Scalar Subtraction
[[0. 1. 2.]
 [3. 4. 5.]]
Scalar Multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
Scalar Division
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


## Data Processing Using Array

Using NumPy arrays enables you to express many kinds of data processing tasks as concise array expressions that might otherwise require writing loops. This practice of replacing explicit loops with array expressions is commonly referred to as vectorization.

### Indexing and Slicing

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [153]:
list1 = [10,20,1,121,13,532,12]
print(list1)

[10, 20, 1, 121, 13, 532, 12]


In [172]:
print(list1[4])
print(list1[4:])
print(list1[:4])
print(list1[2:4])
print(list1[2:6])
print(list1[-1:])
print(list1[:-1])

13
[13, 532, 12]
[10, 20, 1, 121]
[1, 121]
[1, 121, 13, 532]
[12]
[10, 20, 1, 121, 13, 532]


In [173]:
# Slicing single dimension numpy arrays is the same as python lists
arr1 = np.array([10,20,1,121,13,532,12])
print(arr1)

[ 10  20   1 121  13 532  12]


In [174]:
print(arr1[4])
print(arr1[4:])
print(arr1[:4])
print(arr1[2:4])
print(arr1[2:6])
print(arr1[-1:])
print(arr1[:-1])

13
[ 13 532  12]
[ 10  20   1 121]
[  1 121]
[  1 121  13 532]
[12]
[ 10  20   1 121  13 532]


In [114]:
arr = np.array([10,21,312,12,31,53,563,536,632])

print("My Array is:")
print(arr)

print("Extract 5th index from the array")
print(arr[5])

print("Slice 5th to 7th index in array")
print(arr[5:8])

My Array is:
[ 10  21 312  12  31  53 563 536 632]
Extract 5th index from the array
53
Slice 5th to 7th index in array
[ 53 563 536]


In [9]:
print(arr[5:])
print(arr[-1])

[ 53 563 536 632]
632


In [118]:
lst1 = [0,1,2,3,4,5,6,7,8,9]
print(lst1)

lst1[5:8] = 12
print(lst1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


TypeError: can only assign an iterable

In [119]:
arr1 = np.arange(10)
arr1[5:8] = 12
print(arr1)

[ 0  1  2  3  4 12 12 12  8  9]


In [5]:
lst1 = [1,2,3,4,5]
lst1[1] = 12
lst1


[1, 12, 3, 4, 5]

In [125]:
arr1 = np.array([1,2,3,4])

arr2 = arr1
arr2[0] = 100

print(arr1)
print(arr2)

print("##### Deep Copy ####")

arr1 = np.array([1,2,3,4])

arr2 = arr1.copy() ## Deep copy.. arr2 points to a new mem location
arr2[0] = 100

print(arr1)
print(arr2)

[100   2   3   4]
[100   2   3   4]
##### Deep Copy ####
[1 2 3 4]
[100   2   3   4]


In [25]:
#Update the Slice which is different from List

#Array slices are views on the original array.
#This means that the data is not copied, and any modifications to 
#the view will be reflected in the source array
arr1 = np.arange(10)
arr_slice = arr1[5:8]
arr_slice[1] = 12345
print(arr1)

#Not true in case of list
lst1 = [0,1,2,3,4,5,6,7,8,9]
lst_slice = lst1[5:8]
lst_slice[1] = 12345
print(lst1)
print(lst_slice)

##As NumPy has been designed with large data use cases in mind, 
#you could imagine performance and
##memory problems if NumPy insisted on copying data left and right.

[    0     1     2     3     4     5 12345     7     8     9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[5, 12345, 7]


In [159]:
#In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:
import numpy as np
np.random.seed(0)
x2 = np.random.randint(low = 10, high=20, size=(3, 4))  # Two-dimensional array

print("Original Array: \n",x2)

print("Slice :",x2[(0, 0)])

print("Slice :",x2[(0, -1)])

Original Array: 
 [[15 10 13 13]
 [17 19 13 15]
 [12 14 17 16]]
Slice : 15
Slice : 13


In [156]:
import numpy as np
np.random.seed(0)
x2 = np.random.randint(10, size=(3, 4,2))  # Two-dimensional array

print("Original Array: \n",x2)

print("Slice :",x2[(0, 0,0)])

print("Slice :",x2[(0, -1,-1)])

Original Array: 
 [[[5 0]
  [3 3]
  [7 9]
  [3 5]]

 [[2 4]
  [7 6]
  [8 8]
  [1 6]]

 [[7 7]
  [8 1]
  [5 9]
  [8 9]]]
Slice : 5
Slice : 5


If you want a copy of a slice of an ndarray instead of a view, you will
need to explicitly copy the array; for example arr[5:8].copy().

In [157]:
#Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, 
#that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. 
x1 = np.arange(10)
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Array Slicing: Accessing Subarrays

ust as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

In [170]:
x2

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16]])

In [164]:
x2[1:]

array([[17, 19, 13, 15],
       [12, 14, 17, 16]])

In [165]:
x2[:3, :2]

array([[15, 10],
       [17, 19],
       [12, 14]])

In [172]:
x2[1:, 1]

(2,)

In [180]:
#Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

print("Origina Array :\n",x2)
print("Two Row and three Column: \n",x2[:2, :3])
print("Rows until 3rd Index and first 2 columns :\n",x2[:3, :2])

Origina Array :
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Two Row and three Column: 
 [[3 5 2]
 [7 6 8]]
Rows until 3rd Index and first 2 columns :
 [[3 5]
 [7 6]
 [1 6]]


## Transposing: 

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method

Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array

Transposing is a special form of reshaping which similarly returns a view on the underlying data without copying anything. Arrays have the transpose method and also the special T attribute

In [176]:
x2 # (shape mxn)

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16]])

In [185]:
x2.shape

(3, 4)

In [186]:
print(x2)
print(x2.shape)
print(x2.T) # Transposed matrix 
print(x2.T.shape) # shape of transposed matrix # (shape nxm)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
(3, 4)
[[3 7 1]
 [5 6 6]
 [2 8 7]
 [4 8 7]]
(4, 3)


In [205]:
arr = np.arange(18)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [206]:
arr.reshape((3,5))

ValueError: cannot reshape array of size 18 into shape (3,5)

In [207]:
arr.reshape((3,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [197]:
arr.reshape((3, 2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [148]:
arr = np.arange(24)

In [154]:
arr.reshape((2, 3, 4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [77]:
arr = np.arange(24).reshape((2, 3, 4))
print(arr)


print("Transposed Array\n",arr.T)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Transposed Array
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [165]:
#Simple transposing with .T is just a special case of swapping axes. ndarray has the method 
#swapaxes which takes a pair of axis numbers:

arr1 = np.arange(24).reshape(2, 3, 4)

print(arr1)
print(arr1.shape)

print("---------")
print(arr1.swapaxes(0, 1))
print(arr1.swapaxes(0, 1).shape)

#swapaxes similarly returns a view on the data without making a copy.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
---------
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4)


In [204]:
%%timeit 

list1 = range(100000)
# sqrt_list = []
# for i in list1:
#     sqrt_list.append(i**0.5)
sqrt_list = [i**0.5 for i in list1] # list comprehension

16.8 ms ± 404 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [203]:
%%timeit 

arr1 = np.arange(100000)
srtd_arr = np.sqrt(arr1)

460 µs ± 42.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [177]:
#Universal Functions: Fast Element-wise Array Functions

arr = np.arange(10)
print("Original Array :\n",arr)
#x = randn(8)
print("Sqrt Array :\n",np.sqrt(arr))

print("Exp Array: \n",np.exp(arr))

Original Array :
 [0 1 2 3 4 5 6 7 8 9]
Sqrt Array :
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Exp Array: 
 [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [2]:
#add or maximum, take 2 arrays and return a single array as the result:
import numpy as np
x = np.random.randn(8)
y = np.random.randn(8)

print("First Matrix:\n",x)


print("Second Matrix:\n",y)


print("Add both Matrix:\n",np.add(x,y))
print("Find Maximum Elmentwise in Both Matrix",np.maximum(x,y))

First Matrix:
 [ 0.7676349  -1.4108597  -0.51188286  0.75685053 -0.36907004 -0.89319372
 -1.09165776  0.2189898 ]
Second Matrix:
 [ 0.55962326 -1.000064   -1.41701936 -0.29490414 -1.12285359 -2.11449554
  0.17668923  0.62342428]
Add both Matrix:
 [ 1.32725816 -2.4109237  -1.92890222  0.46194639 -1.49192363 -3.00768927
 -0.91496853  0.84241408]
Find Maximum Elmentwise in Both Matrix [ 0.7676349  -1.000064   -0.51188286  0.75685053 -0.36907004 -0.89319372
  0.17668923  0.62342428]


## Mathematical and Statistical Methods

A set of mathematical functions which compute statistics about an entire array or about the data along an axis are accessible as array methods. Aggregations (often called reductions) like sum, mean, and standard deviation std can either be used by calling the array instance method:

In [212]:
arr = np.array([[20,24,30,22,55],
                [10,210,120,21,2120],
               [21,35,35, 72, 84]])

In [213]:
arr

array([[  20,   24,   30,   22,   55],
       [  10,  210,  120,   21, 2120],
       [  21,   35,   35,   72,   84]])

In [214]:
arr.diagonal()

array([ 20, 210,  35])

In [215]:
arr.min()

10

In [216]:
arr.max()

2120

In [217]:
arr.flatten()

array([  20,   24,   30,   22,   55,   10,  210,  120,   21, 2120,   21,
         35,   35,   72,   84])

In [218]:
arr

array([[  20,   24,   30,   22,   55],
       [  10,  210,  120,   21, 2120],
       [  21,   35,   35,   72,   84]])

In [219]:
arr.cumsum(axis=0)

array([[  20,   24,   30,   22,   55],
       [  30,  234,  150,   43, 2175],
       [  51,  269,  185,  115, 2259]], dtype=int32)

In [220]:
arr.cumsum(axis=1)

array([[  20,   44,   74,   96,  151],
       [  10,  220,  340,  361, 2481],
       [  21,   56,   91,  163,  247]], dtype=int32)

In [221]:
arr.cumsum()

array([  20,   44,   74,   96,  151,  161,  371,  491,  512, 2632, 2653,
       2688, 2723, 2795, 2879], dtype=int32)

In [226]:
print("Array is:\n",arr)

print("Mean is: ",arr.mean())
print("Mean is:", np.mean(arr))

print("Row Mean is: ",arr.mean(axis=1))
print("Column Mean is:", arr.mean(axis=0))


print("Sum is:", arr.sum())
print("Sum is:", np.sum(arr))




Array is:
 [[  20   24   30   22   55]
 [  10  210  120   21 2120]
 [  21   35   35   72   84]]
Mean is:  191.93333333333334
Mean is: 191.93333333333334
Row Mean is:  [ 30.2 496.2  49.4]
Column Mean is: [ 17.          89.66666667  61.66666667  38.33333333 753.        ]
Sum is: 2879
Sum is: 2879


Functions like mean and sum take an optional axis argument which computes the statistic over the given axis, resulting in an array with one fewer dimension:

In [229]:
arr.sum(axis=1)

array([ 151, 2481,  247])

In [228]:
arr.sum(axis=0)

array([  51,  269,  185,  115, 2259])

In [230]:
print(arr)
arr.mean(axis=1)

[[  20   24   30   22   55]
 [  10  210  120   21 2120]
 [  21   35   35   72   84]]


array([ 30.2, 496.2,  49.4])

In [15]:
np.mean(arr,axis=0)

array([-0.58425131, -0.47510068, -0.24684652,  0.17977643])

Other methods like cumsum and cumprod do not aggregate, instead producing an array of the intermediate results:

In [56]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
arr.cumsum(1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [57]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [231]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print("Array is :\n",arr)

print("Cumulative Sum Rowwise: \n",arr.cumsum(0))

print("Cumulative Sum Columwise: \n",arr.cumsum(1))

print("Cumulative Product Rowwise: \n",arr.cumprod(0))

print("Cumulative Product Columwise: \n",arr.cumprod(1))

Array is :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Cumulative Sum Rowwise: 
 [[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
Cumulative Sum Columwise: 
 [[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
Cumulative Product Rowwise: 
 [[ 0  1  2]
 [ 0  4 10]
 [ 0 28 80]]
Cumulative Product Columwise: 
 [[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [233]:
#Sorting:
import numpy as np
arr = np.random.randint(15, size= (3, 5))

print("Original Array: \n",arr)
#np.sort returns a sorted copy of an array
arr.sort(axis=0)
print("Sortd Array Row wise: \n",arr)
arr.sort(axis=1)
print("Sortd Array Column wise: \n",arr)




Original Array: 
 [[ 4  3 12 13 14]
 [ 0  4  3 13 11]
 [12  6 13  9 13]]
Sortd Array Row wise: 
 [[ 0  3  3  9 11]
 [ 4  4 12 13 13]
 [12  6 13 13 14]]
Sortd Array Column wise: 
 [[ 0  3  3  9 11]
 [ 4  4 12 13 13]
 [ 6 12 13 13 14]]


In [238]:
#NumPy has some basic set operations for one-dimensional ndarrays. Probably the most
#commonly used one is np.unique, which returns the sorted unique values in an array

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names.sort(axis=0)
print(names)
print("Unique Values in Array (Sorted Order) :",np.unique(names))

['Bob' 'Bob' 'Joe' 'Joe' 'Joe' 'Will' 'Will']
Unique Values in Array (Sorted Order) : ['Bob' 'Joe' 'Will']


## Random Number Generation

The numpy.random module supplements the built-in Python random with functions for efficiently generating whole arrays of sample values from the standard differennt distributions

    rand: Draw samples from a uniform distribution
    randint: Draw random integers from a given low-to-high range
    randn: Draw samples from a normal distribution (Standard Normal)
    binomial: Draw samples a binomial distribution
    normal: Draw samples from a normal (Gaussian) distribution
    chi-square: Draw samples from a chi-square distribution
    uniform: Draw samples from a uniform [0, 1) distribution
    

In [ ]:
np.random.randint() # Return random integers from uniform dist
np.random.uniform() # Return random values from uniform dist
np.random.normal() # Returns values from normal dist
np.random.randn() # Returns values from normal dist

In [240]:
np.random.randint(low = 10, high = 20, size= (3, 3) )

array([[18, 10, 18],
       [15, 19, 10],
       [19, 16, 15]])

In [244]:
np.random.normal(loc = 27, # mean 
                 scale = 3, # stdev
                 size= (3, 3)) # shape

array([[26.55109638, 25.69453934, 32.54779119],
       [29.01688427, 28.22238551, 24.69025178],
       [28.61774757, 24.97700202, 27.09549167]])

In [245]:
np.random.randn(3, 3) # mean = 0, stdev = 1, standard normal distribution

array([[-0.63584608,  0.67643329,  0.57659082],
       [-0.20829876,  0.39600671, -1.09306151],
       [-1.49125759,  0.4393917 ,  0.1666735 ]])

In [247]:
samples = np.random.uniform(1, 20, size = (3,3))
print(samples)

[[10.31871736  5.32087793  5.83277315]
 [ 2.10255405  9.25391589  6.92412176]
 [14.23052629  8.17728495  4.41246987]]


### Matrix multiplication

In [248]:
arr1 = np.random.randint(10, size = (2,3))
arr2 = np.random.randint(10, size = (2,3))

In [249]:
arr1

array([[5, 9, 9],
       [2, 0, 9]])

In [250]:
arr2

array([[1, 9, 0],
       [6, 0, 4]])

In [251]:
arr1*arr2 # Elementwise multiplication

array([[ 5, 81,  0],
       [12,  0, 36]])

In [253]:
np.matmul(arr1.T, arr2)

array([[17, 45,  8],
       [ 9, 81,  0],
       [63, 81, 36]])

In [254]:
np.matmul(arr1, arr2.T)

array([[86, 66],
       [ 2, 48]])

In [255]:
np.matmul(arr2.T, arr1 )

array([[17,  9, 63],
       [45, 81, 81],
       [ 8,  0, 36]])

## Combine Matrices

In [256]:
arr1 = np.random.randint(10, size = (2,3))
arr2 = np.random.randint(10, size = (2,3))

In [257]:
arr1

array([[8, 4, 3],
       [3, 8, 8]])

In [258]:
arr2

array([[7, 0, 3],
       [8, 7, 7]])

In [260]:
np.concatenate((arr1, arr2), axis=1) # Columnwise

array([[8, 4, 3, 7, 0, 3],
       [3, 8, 8, 8, 7, 7]])

In [261]:
np.concatenate((arr1, arr2), axis=0)# Rowwise

array([[8, 4, 3],
       [3, 8, 8],
       [7, 0, 3],
       [8, 7, 7]])

In [262]:
arr3 = np.array([1,2,3])
arr4 = np.array([4, 5, 6])

In [263]:
np.concatenate((arr3, arr4)) # horizontally concatenated

array([1, 2, 3, 4, 5, 6])

In [264]:
np.hstack((arr3, arr4)) # horizontally concatenated

array([1, 2, 3, 4, 5, 6])

In [265]:
np.vstack((arr3, arr4)) # vertically concatenated

array([[1, 2, 3],
       [4, 5, 6]])

In [266]:
np.column_stack((arr3, arr4)) # each array is turned into a column

array([[1, 4],
       [2, 5],
       [3, 6]])